import { AuditResult } from "../genkit/flows/audit";

/**
 * Format audit result for output file
 */
export function formatAuditResultForOutput(result: AuditResult): string {
  return `# Firestore Security Rules Audit

## Summary
${result.summary}

## Security Rating
**${result.overallRating}/10**

## Vulnerabilities
${
  result.vulnerabilities.length === 0
    ? "No vulnerabilities found."
    : result.vulnerabilities
        .map(
          (v) => `### [${v.severity.toUpperCase()}] ${v.description}
- **Recommendation:** ${v.recommendation}
${v.location ? `- **Location:** ${v.location}` : ""}`
        )
        .join("\n\n")
}

## Best Practices
${result.bestPractices.map((bp, i) => `${i + 1}. ${bp}`).join("\n")}

---
Generated by Firestore Security Auditor on ${new Date().toISOString()}
`;
}
